module.exports = {
  apps: [
    {
      name: 'api-fdx-env',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ["src/helpers/Guias"],
      max_memory_restart: '1G',
      env: {
        PORT:4010,
        PATH_GUIA:'var/www/devback/Pakki_Rest/src/helpers/Guias',
        URL_GUIA:'https://devfront.pakki.click/guias',
        ROOT_API:'/api/v1',
        ENVIROMENT:'Development Server Api_fdx',
        MONGO_URL:'mongodb://127.0.0.1:27017/devpakkiDB',
        USERDB:'devappakki',
        PWDDB:'4Pp4kk1',        
        JWT_SECRET:'**Enl4c4s4d3p1n0ch0t0d0scu3nt4nh4st40ch0@@',
        DEBUG_MODE:true,        
        FDX_URL: 'https://apis.fedex.com/ship/v1/shipments',
        FDX_SHIPMENT_URL: 'https://apis.fedex.com/ship/v1/shipments',
        FDX_SHIPMENT_VALIDATE_URL: 'https://apis.fedex.com/ship/v1/shipments/packages/validate',
        FDX_SHIPMENT_CANCEL_URL: 'https://apis.fedex.com/ship/v1/shipments/cancel',
        FDX_QUOTATION_URL: 'https://apis.fedex.com/rate/v1/rates/quotes',
        FDX_PICKUP_SHIPMENT_URL: 'https://apis.fedex.com/pickup/v1/pickups',
        FDX_URL_TOKEN: 'https://apis.fedex.com/oauth/token',
        FDX_CLIENT_ID_CO: 'l700a872647ffc40d59a610f6459ff5536',
        FDX_CLIENT_SECRET_CO: '5141f2e3-2fef-4d1c-b3d0-de0373083772',
        FDX_ACCOUNT_CO: '203128530',
      },
    },
    {
      name: 'api-fdx-prod',
      script: 'npm',
      args: 'run prod',
      instances: 1,
      autorestart: true,
      watch: true,
      ignore_watch: ["src/helpers/Guias"],
      max_memory_restart: '1G',
      prod: {
        PORT: 4011,
        PATH_GUIA: 'var/www/devback/Pakki_Rest/src/helpers/Guias',
        URL_GUIA: 'https://devfront.pakki.click/guias',
        ROOT_API: '/api/v1',
        ENVIROMENT: 'Production Server Api_fdx',
        MONGO_URL: 'mongodb://127.0.0.1:27017/pakkiDB',
        JWT_SECRET: '**Enl4c4s4d3p1n0ch0t0d0scu3nt4nh4st40ch0@@',
        DEBUG_MODE: true,
        FDX_URL: 'https://apis.fedex.com/ship/v1/shipments',
        FDX_SHIPMENT_URL: 'https://apis.fedex.com/ship/v1/shipments',
        FDX_SHIPMENT_VALIDATE_URL: 'https://apis.fedex.com/ship/v1/shipments/packages/validate',
        FDX_SHIPMENT_CANCEL_URL: 'https://apis.fedex.com/ship/v1/shipments/cancel',
        FDX_QUOTATION_URL: 'https://apis.fedex.com/rate/v1/rates/quotes',
        FDX_PICKUP_SHIPMENT_URL: 'https://apis.fedex.com/pickup/v1/pickups',
        FDX_URL_TOKEN: 'https://apis.fedex.com/oauth/token',
        FDX_CLIENT_ID_CO: 'l700a872647ffc40d59a610f6459ff5536',
        FDX_CLIENT_SECRET_CO: '5141f2e3-2fef-4d1c-b3d0-de0373083772',
        FDX_ACCOUNT_CO: '203128530',
      }
    }    
  ]
};